"""Build local sprite sheets from a pinned PokéAPI sprites revision.

Requires ImageMagick 7 (`magick`). Run `python3 scripts/generate_sprites.py`.
The source images are Pokémon artwork and are not covered by the app's code license.
"""

from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import subprocess
import tempfile
import time
import urllib.request


ROOT = Path(__file__).resolve().parents[1]
REVISION = "fb3512817b9c3f46952b3f89e82645e77bdcaf49"
BASE_URL = f"https://raw.githubusercontent.com/PokeAPI/sprites/{REVISION}/sprites/pokemon"
RANGES = [(1, 151), (152, 251), (252, 386), (387, 493), (494, 649),
          (650, 721), (722, 809), (810, 905), (906, 1025)]
CELL = 40
COLUMNS = 16
OUTPUT = ROOT / "public" / "sprites"
MANIFEST = ROOT / "src" / "sprite-sheets.ts"


def download(number: int, directory: Path) -> Path:
    path = directory / f"{number}.png"
    request = urllib.request.Request(
        f"{BASE_URL}/{number}.png",
        headers={"User-Agent": "EffortValuesPlanner/1.0 (sprite generation)"},
    )
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                content = response.read()
            if not content.startswith(b"\x89PNG\r\n\x1a\n"):
                raise ValueError(f"Sprite {number} is not a PNG")
            path.write_bytes(content)
            return path
        except (OSError, ValueError):
            if attempt == 2:
                raise
            time.sleep(attempt + 1)
    raise AssertionError("unreachable")


def prepare(number: int, source: Path, directory: Path) -> Path:
    path = directory / f"{number}.png"
    subprocess.run(
        ["magick", str(source), "-trim", "+repage", "-filter", "point",
         "-resize", "32x32>", "-gravity", "center", "-background", "none",
         "-extent", f"{CELL}x{CELL}", str(path)],
        check=True,
        stdout=subprocess.DEVNULL,
    )
    return path


def main() -> None:
    subprocess.run(["magick", "-version"], check=True, stdout=subprocess.DEVNULL)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="effort-values-sprites-") as temp:
        source = Path(temp) / "source"
        tiles = Path(temp) / "tiles"
        source.mkdir()
        tiles.mkdir()
        numbers = range(1, RANGES[-1][1] + 1)
        with ThreadPoolExecutor(max_workers=16) as pool:
            originals = list(pool.map(lambda number: download(number, source), numbers))
        with ThreadPoolExecutor(max_workers=8) as pool:
            list(pool.map(lambda item: prepare(item[0], item[1], tiles),
                          zip(numbers, originals)))
        for generation, (start, end) in enumerate(RANGES, 1):
            paths = [str(tiles / f"{number}.png") for number in range(start, end + 1)]
            output = OUTPUT / f"gen{generation}.png"
            subprocess.run(
                ["magick", "montage", *paths, "-tile", f"{COLUMNS}x",
                 "-geometry", "+0+0", "-background", "none", str(output)],
                check=True,
                stdout=subprocess.DEVNULL,
            )
            print(f"Generation {generation}: #{start}–{end}, {output.stat().st_size:,} bytes")
    rows = ",\n".join(
        f"  {{ generation: {generation}, start: {start}, end: {end} }}"
        for generation, (start, end) in enumerate(RANGES, 1)
    )
    MANIFEST.write_text(
        "// Generated by scripts/generate_sprites.py. Do not edit manually.\n"
        f"export const spriteCellSize = {CELL};\n"
        f"export const spriteColumns = {COLUMNS};\n"
        f"export const spriteSheets = [\n{rows},\n] as const;\n"
    )


if __name__ == "__main__":
    main()
